export default [
  { name: 'Chicken Back', value: 44, key: 'Chicken-Back' },
  { name: 'Chicken Breast', value: 20, key: 'Chicken-Breast' },
  { name: 'Chicken Drumstick', value: 27, key: 'Chicken-Drumstick' },
  { name: 'Chicken Feet', value: 60, key: 'Chicken-Feet' },
  { name: 'Chicken Frame', value: 80, key: 'Chicken-Frame' },
  { name: 'Chicken Leg Quarter', value: 30, key: 'Chicken-Leg-Quarter' },
  { name: 'Chicken Neck with Skin', value: 36, key: 'Chicken-Neck-with-Skin' },
  { name: 'Chicken Neck without Skin', value: 50, key: 'Chicken-Neck-without-Skin' },
  { name: 'Chicken Thigh', value: 21, key: 'Chicken-Thigh' },
  { name: 'Chicken Whole', value: 32, key: 'Chicken-Whole' },
  { name: 'Chicken Wings', value: 46, key: 'Chicken-Wings' },
  { name: 'Duck Foot', value: 60, key: 'Duck-Foot' },
  { name: 'Duck Frame', value: 80, key: 'Duck-Frame' },
  { name: 'Duck Neck', value: 50, key: 'Duck-Neck' },
  { name: 'Duck Whole', value: 28, key: 'Duck-Whole' },
  { name: 'Duck Wing', value: 39, key: 'Duck-Wing' },
  { name: 'Pork Feet', value: 30, key: 'Pork-Feet' },
  { name: 'Pork Ribs', value: 30, key: 'Pork-Ribs' },
  { name: 'Pork Tail', value: 30, key: 'Pork-Tail' },
  { name: 'Rabbit Feet', value: 40, key: 'Rabbit-Feet' },
  { name: 'Rabbit Heads', value: 75, key: 'Rabbit-Heads' },
  { name: 'Rabbit Whole', value: 28, key: 'Rabbit-Whole' },
  { name: 'Turkey Neck', value: 45, key: 'Turkey-Neck' },
  { name: 'Custom', value: 0, key: 'Custom' },
];
