export default [
  { name: 'Chicken Back (44%)', value: 44, key: 'Chicken-Back' },
  { name: 'Chicken Breast (20%)', value: 20, key: 'Chicken-Breast' },
  { name: 'Chicken Drumstick (27%)', value: 27, key: 'Chicken-Drumstick' },
  { name: 'Chicken Feet (60%)', value: 60, key: 'Chicken-Feet' },
  { name: 'Chicken Frame (80%)', value: 80, key: 'Chicken-Frame' },
  { name: 'Chicken Leg Quarter (30%)', value: 30, key: 'Chicken-Leg-Quarter' },
  { name: 'Chicken Neck with Skin (36%)', value: 36, key: 'Chicken-Neck-with-Skin' },
  { name: 'Chicken Neck without Skin (50%)', value: 50, key: 'Chicken-Neck-without-Skin' },
  { name: 'Chicken Thigh (21%)', value: 21, key: 'Chicken-Thigh' },
  { name: 'Chicken Whole (32%)', value: 32, key: 'Chicken-Whole' },
  { name: 'Chicken Wings (46%)', value: 46, key: 'Chicken-Wings' },
  { name: 'Duck Foot (60%)', value: 60, key: 'Duck-Foot' },
  { name: 'Duck Frame (80%)', value: 80, key: 'Duck-Frame' },
  { name: 'Duck Neck (50%)', value: 50, key: 'Duck-Neck' },
  { name: 'Duck Whole (28%)', value: 28, key: 'Duck-Whole' },
  { name: 'Duck Wing (39%)', value: 39, key: 'Duck-Wing' },
  { name: 'Pork Feet (30%)', value: 30, key: 'Pork-Feet' },
  { name: 'Pork Ribs (30%)', value: 30, key: 'Pork-Ribs' },
  { name: 'Pork Tail (30%)', value: 30, key: 'Pork-Tail' },
  { name: 'Rabbit Feet (40%)', value: 40, key: 'Rabbit-Feet' },
  { name: 'Rabbit Heads (75%)', value: 75, key: 'Rabbit-Heads' },
  { name: 'Rabbit Whole (28%)', value: 28, key: 'Rabbit-Whole' },
  { name: 'Turkey Neck (45%)', value: 45, key: 'Turkey-Neck' },
  { name: 'Custom', value: 0, key: 'Custom' },
];
